### PR TITLE
Cleanup the code a bit

### PR DESCRIPTION
**Pull request by schriftgestalt**
I changed the factors a bit to my taste (to be more useful for text fonts).

### CODE REVIEW

**Comment by jpt** [comment]
@schriftgestalt thank you for the cleanup! 🧹

Unfortunately the equal sign is not doing very well for some masters. I will take a look. the basis for spacing had previously been `n.LSB` + `n.RSB`


Screen Shot 2021-09-03 at 9 28 46 AM

**Comment by schriftgestalt** [comment]
Right. It didn’t looked so good for the serif font I was looking at (because there, the side bearings are quite small.

**Comment by jpt** [comment]
> Right. It didn’t looked so good for the serif font I was looking at (because there, the side bearings are quite small.

ah, got it. What I'll do is use `intersectionBetweenPoints` along the x-axis at half the x-height to measure the sides of the `n`, so we can use that instead of the `LSB` and `RSB` (which, in the sans I was testing on, is equivalent)

**Comment by jpt** [comment]
@schriftgestalt I made some changes ( 6b6f515daaba00c97f2534d092eb10f55375e192) and merged

let me know if there is still a problem for a serif font. it now measures the `n` counter space at `xHeight/3`

**Pull request merged**
